"""
Send the trend summary report via email using Python's built-in smtplib.

Configuration is read from environment variables:
  EMAIL_SMTP_HOST     – SMTP server hostname (default: smtp.gmail.com)
  EMAIL_SMTP_PORT     – SMTP server port (default: 587)
  EMAIL_SENDER        – sender email address (required)
  EMAIL_PASSWORD      – sender password or app-specific password (required)
  EMAIL_RECIPIENTS    – comma-separated list of recipient addresses (required)
"""

from __future__ import annotations

import os
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from process.summarize import TrendSummary


def _build_html_report(summaries: list[TrendSummary]) -> str:
    """Build an HTML version of the trend report for richer email rendering."""
    rows: list[str] = []
    for s in summaries:
        links = "".join(f'<li><a href="{url}">{url}</a></li>' for url in s.top_urls)
        countries = f"<br>Countries: {', '.join(s.countries)}" if s.countries else ""
        rows.append(
            f"<tr>"
            f'<td style="padding:8px;vertical-align:top;font-weight:bold;">#{s.rank}</td>'
            f'<td style="padding:8px;">'
            f"<strong>{s.headline}</strong><br>"
            f"Score: {s.score:.2f} &middot; {s.article_count} articles &middot; {s.source_count} sources<br>"
            f"Date range: {s.date_range}"
            f"{countries}<br>"
            f"<ul>{links}</ul>"
            f"</td>"
            f"</tr>"
        )

    table_rows = "\n".join(rows)
    return (
        "<html><body>"
        '<h2 style="color:#333;">News Trends Summary</h2>'
        '<table border="0" cellspacing="0" cellpadding="0" '
        'style="border-collapse:collapse;width:100%;max-width:700px;">'
        f"{table_rows}"
        "</table>"
        '<p style="color:#999;font-size:12px;">Generated by NewsTrendsSummary</p>'
        "</body></html>"
    )


def send_email(
    summaries: list[TrendSummary],
    plain_text_report: str,
    *,
    smtp_host: str | None = None,
    smtp_port: int | None = None,
    sender: str | None = None,
    password: str | None = None,
    recipients: list[str] | None = None,
    subject: str = "News Trends Summary",
) -> None:
    """
    Send the trend report as a multipart (plain-text + HTML) email.

    Parameters fall back to environment variables when not provided.
    Raises ValueError if required config is missing.
    """
    host = smtp_host or os.environ.get("EMAIL_SMTP_HOST", "smtp.gmail.com")
    port = smtp_port or int(os.environ.get("EMAIL_SMTP_PORT", "587"))
    from_addr = sender or os.environ.get("EMAIL_SENDER", "")
    pwd = password or os.environ.get("EMAIL_PASSWORD", "")
    to_addrs = recipients or [
        r.strip()
        for r in os.environ.get("EMAIL_RECIPIENTS", "").split(",")
        if r.strip()
    ]

    if not from_addr:
        raise ValueError("EMAIL_SENDER is required (env var or parameter)")
    if not pwd:
        raise ValueError("EMAIL_PASSWORD is required (env var or parameter)")
    if not to_addrs:
        raise ValueError("EMAIL_RECIPIENTS is required (env var or parameter)")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = ", ".join(to_addrs)

    msg.attach(MIMEText(plain_text_report, "plain"))
    msg.attach(MIMEText(_build_html_report(summaries), "html"))

    context = ssl.create_default_context()
    with smtplib.SMTP(host, port) as server:
        server.starttls(context=context)
        server.login(from_addr, pwd)
        server.sendmail(from_addr, to_addrs, msg.as_string())
